### ISSUE TITLE
Fake l ol

### ISSUE THREAD

**Issue by WiiZARDD** [takeyo93/SnakeGEN-Python-Token-Nitro-Generator-Checkers#1]
Does not work will almost always provide invalid gift links, just a troll l ol

**Comment by takeyo93** [comment]
hi kid, you know no generator gives valid nitro? if you don't know stop talking, it's not for nothing that there is a checker to see if they are valid.

**Comment by WiiZARDD** [comment]
> hi kid, you know no generator gives valid nitro? if you don't know stop talking, it's not for nothing that there is a checker to see if they are valid.

then quit posting like a skid l ol

**Comment by WiiZARDD** [comment]
clearly you posted a generator with 0 purpose bahahahaa
